#!/usr/bin/env python3.8

#Exercise 2: Working with If/Else
user = {'admin': True, 'active': False, 'name': 'Nikos'}

if user['admin'] and user['active']:
    print(f"ACTIVE - (ADMIN) {user['name']}")
elif user['admin']:
    print(f"(ADMIN) {user['name']}")
elif user['active']:
    print(f"ACTIVE - {user['name']}")
else:
    print(f"{user['name']}")
