#!/home/nal3x/venvs/experiment/bin/python
import os
import requests
import sys

from argparse import ArgumentParser

parser = ArgumentParser(description='Get the current weather information')
parser.add_argument('city_name', help='city name to get the weather for')
parser.add_argument('--country_code', default='gr', help='country code the city belongs to, ISO 3166')

args = parser.parse_args()

api_key = os.getenv('OWM_API_KEY')

if not api_key:
    print("Error: no API key provided")
    sys.exit(1)

url = (
        f"http://api.openweathermap.org/data/2.5/weather?"
        f"q={args.city_name},{args.country_code}"
        f"&APPID={api_key}"
)

res = requests.get(url)

if res.status_code != 200:
    print(f"Error talking to weather provider: {res.status_code}")
    sys.exit(1)

print(res.json())
