#!/usr/bin/env python3.8

#Exercise 3: Iterating over Lists
user1 = {'admin': True, 'active': True, 'name': 'Nikos'}
user2 = {'admin': False, 'active': True, 'name': 'Niki'}
user3 = {'admin': True, 'active': False, 'name': 'Vangelis'}

users_list = [user1, user2, user3]
line_number = 1

for user in users_list:
    prefix = str(line_number) + " "

    if user['active']:
        prefix += "ACTIVE - "
    if user['admin']:
        prefix += "(ADMIN) "

    print(prefix + user['name'])
    line_number += 1
