#!/usr/bin/env python3.8
import argparse
import sys

def positive(string):
    value = int(string)
    if value <= 0:
        msg = f"{value} is not a positive number"
        raise argparse.ArgumentTypeError(msg)
    return value

parser = argparse.ArgumentParser(description='Print specified line number from given file')
parser.add_argument('filename', help='The file to read')
parser.add_argument('line_number', type=positive, help='The number of line to print (positive values only)')

args = parser.parse_args()

try:
    file = open(args.filename)
    line = file.readlines()[args.line_number - 1].strip()
except FileNotFoundError as err:
    print(f"Error: {err}")
    sys.exit(1)
except IndexError as err:
    print(f"Error: the file does not contain the line number specified")
    sys.exit(2)
else:
    print(line)
    file.close()
